apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-serveractions-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ghcr.io/tuna2134/hello-serveractions:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: NEXT_PUBLIC_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: hello-severactions-secret
              key: secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: hello-serveractions
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
